export const COLORS = {
  primary: '#004ac6',
  primaryContainer: '#2563eb',
  primaryFixed: '#dbe1ff',
  primaryFixedDim: '#b4c5ff',
  secondary: '#712ae2',
  secondaryContainer: '#8a4cfc',
  secondaryFixed: '#eaddff',
  secondaryFixedDim: '#d2bbff',
  tertiary: '#006229',
  tertiaryContainer: '#007e37',
  tertiaryFixed: '#6bff8f',
  tertiaryFixedDim: '#4ae176',
  background: '#f8f9fa',
  surface: '#ffffff',
  surfaceContainerLow: '#f3f4f5',
  surfaceContainerHigh: '#e7e8e9',
  surfaceContainerHighest: '#ffffff',
  onSurface: '#191c1d',
  onSurfaceVariant: '#5f6671',
  onPrimary: '#ffffff',
  onPrimaryFixed: '#00174b',
  onPrimaryFixedVariant: '#003ea8',
  onSecondary: '#ffffff',
  onSecondaryFixed: '#25005a',
  onSecondaryFixedVariant: '#5a00c6',
  onTertiary: '#ffffff',
  onTertiaryFixed: '#002109',
  onTertiaryFixedVariant: '#005321',
  gray: '#7b7f8a',
  grayLight: '#d9dadb',
  grayLighter: '#ececec',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onError: '#ffffff',
  onErrorContainer: '#93000a',
  success: '#0f9d58',
  shadow: '#000000',
  white: '#ffffff',
};

export const SCREEN_NAMES = {
  Login: 'Login',
  Signup: 'Signup',
  ForgotPassword: 'ForgotPassword',
  OTP: 'OTP',
  HomeMain: 'HomeMain',
  QRMain: 'QRMain',
  BookSearch: 'BookSearch',
  BookDetail: 'BookDetail',
  FileSharing: 'FileSharing',
  Print: 'Print',
  Profile: 'Profile',
  TransactionHistory: 'TransactionHistory',
  Settings: 'Settings',
  QRScanner: 'QRScanner',
  AttendanceDashboard: 'AttendanceDashboard',
  BiometricVerification: 'BiometricVerification',
  ContactSupport: 'ContactSupport',
  EditPersonalDetails: 'EditPersonalDetails',
  IssueBooks: 'IssueBooks',
  Notifications: 'Notifications',
  PaymentFines: 'PaymentFines',
  PremiumDashboard: 'PremiumDashboard',
  ReturnBooks: 'ReturnBooks',
  ReturnHistory: 'ReturnHistory',
  SuccessConfirmation: 'SuccessConfirmation',
  CampusOverview: 'CampusOverview',
};

export const TABS = {
  HOME: 'Library',
  QR: 'Scan',
  BOOKS: 'Search',
  FILES: 'Print',
};
